In [47]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split

In [48]:
df = pd.read_csv('master_data_table.csv')
df

Unnamed: 0 wals code               name  value       description  \
0               0       kiw   Kiwai (Southern)      1             Small   
1               1       xoo               !Xóõ      5             Large   
2               2       ani              //Ani      5             Large   
3               3       abi             Abipón      2  Moderately small   
4               4       abk             Abkhaz      5             Large   
...           ...       ...                ...    ...               ...   
76470       76470       tbt             Tobati      5  OS(Neg)[V(-Neg)]   
76471       76471       tvl           Tuvaluan      1            ONegVS   
76472       76472       ung         Ungarinjin      1            ONegVS   
76473       76473       urn            Urarina      4         O[V-Neg]S   
76474       76474       wic            Wichita      8     NegOVS/NegSOV   

        latitude   longitude        area  \
0      -8.000000  143.500000   Phonology   
1     -24.000000   21.500000   Phonology   
2     -18.916667   21.916667   Phonology   
3     -29.000000  -61.000000   Phonology   
4      43.083333   41.000000   Phonology   
...          ...         ...         ...   
76470  -2.583333  140.666667  Word Order   
76471  -8.500000  179.166667  Word Order   
76472 -16.333333  126.000000  Word Order   
76473  -4.500000  -75.500000  Word Order   
76474  33.333333  -97.333333  Word Order   

                                                   title  \
0                                  Consonant Inventories   
1                                  Consonant Inventories   
2                                  Consonant Inventories   
3                                  Consonant Inventories   
4                                  Consonant Inventories   
...                                                  ...   
76470  The Position of Negative Morphemes in Object-I...   
76471  The Position of Negative Morphemes in Object-I...   
76472  The Position of Negative Morphemes in Object-I...   
76473  The Position of Negative Morphemes in Object-I...   
76474  The Position of Negative Morphemes in Object-I...   

                                                   entry  
0                                Consonant Inventories 1  
1                                Consonant Inventories 5  
2                                Consonant Inventories 5  
3                                Consonant Inventories 2  
4                                Consonant Inventories 5  
...                                                  ...  
76470  The Position of Negative Morphemes in Object-I...  
76471  The Position of Negative Morphemes in Object-I...  
76472  The Position of Negative Morphemes in Object-I...  
76473  The Position of Negative Morphemes in Object-I...  
76474  The Position of Negative Morphemes in Object-I...  

[76475 rows x 10 columns]

In [49]:
feed1_df = pd.read_csv('./Example Inputs/feed1.csv')
feed1_df = feed1_df.dropna()
feed1_df['entry']

0                     Presence of Uncommon Consonants 1
1     Relationship between the Order of Object and V...
2          Order of Adverbial Subordinator and Clause 2
3                               Consonant Inventories 5
4           Double negation in verb-initial languages 5
5                             Noun Phrase Conjunction 1
6                        The Morphological Imperative 1
7     Minor morphological means of signaling negation 4
8     The Position of Negative Morphemes in SVO Lang...
9                                        SONegV Order 1
10                   Position of Tense-Aspect Affixes 2
11                             The Associative Plural 4
Name: entry, dtype: object

In [50]:
location = list(zip(df.latitude, df.longitude))
df['location'] = location
df['entry'] = df['entry'].str.replace('/', ' or ')

In [51]:
df.head()

Unnamed: 0 wals code               name  value       description  \
0           0       kiw   Kiwai (Southern)      1             Small   
1           1       xoo               !Xóõ      5             Large   
2           2       ani              //Ani      5             Large   
3           3       abi             Abipón      2  Moderately small   
4           4       abk             Abkhaz      5             Large   

    latitude   longitude       area                  title  \
0  -8.000000  143.500000  Phonology  Consonant Inventories   
1 -24.000000   21.500000  Phonology  Consonant Inventories   
2 -18.916667   21.916667  Phonology  Consonant Inventories   
3 -29.000000  -61.000000  Phonology  Consonant Inventories   
4  43.083333   41.000000  Phonology  Consonant Inventories   

                     entry                     location  
0  Consonant Inventories 1                (-8.0, 143.5)  
1  Consonant Inventories 5                (-24.0, 21.5)  
2  Consonant Inventories 5  (-18.91666667, 21.91666667)  
3  Consonant Inventories 2               (-29.0, -61.0)  
4  Consonant Inventories 5          (43.08333333, 41.0)

In [52]:
# entry = df['entry']
# dummies_entry = pd.get_dummies(entry)
# df['dummies_entry'] = dummies_entry
# df

In [152]:
X = df['entry']
z = df['latitude']
y = df['longitude']

feed1_df_X = feed1_df['entry']

X.shape, y.shape

((76475,), (76475,))

In [153]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(X)
# label_encoder.fit(feed1_df_X)
encoded_X = label_encoder.transform(X)
encoded_feed1 = label_encoder.transform(feed1_df_X)



In [154]:
for label, original_class in zip(encoded_feed1, X):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: Consonant Inventories 1
Encoded Label: 803
------------
Original Class: Consonant Inventories 5
Encoded Label: 851
------------
Original Class: Consonant Inventories 5
Encoded Label: 601
------------
Original Class: Consonant Inventories 2
Encoded Label: 100
------------
Original Class: Consonant Inventories 5
Encoded Label: 148
------------
Original Class: Consonant Inventories 2
Encoded Label: 415
------------
Original Class: Consonant Inventories 1
Encoded Label: 959
------------
Original Class: Consonant Inventories 5
Encoded Label: 324
------------
Original Class: Consonant Inventories 2
Encoded Label: 1012
------------
Original Class: Consonant Inventories 3
Encoded Label: 883
------------
Original Class: Consonant Inventories 4
Encoded Label: 762
------------
Original Class: Consonant Inventories 3
Encoded Label: 956
------------


In [155]:
one_hot_X = to_categorical(encoded_X)
one_hot_X_feed1 = to_categorical(encoded_feed1)
# cols = [1,2,3,4,5,6,7,8,9,10]
# df = df[df.columns[cols]]
# df
one_hot_X_feed1[0:3,0:5]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [156]:
# # Step 1: Label-encode data set
# label_encoder = LabelEncoder()
# label_encoder.fit(y)
# encoded_y = label_encoder.transform(y)

In [157]:
# create training and testing data
X_train, X_test, y_train, y_test = train_test_split(encoded_X, y, random_state=1)

In [158]:
# from sklearn.preprocessing import StandardScaler

# # Create a StandardScater model and fit it to the training data

# ### BEGIN SOLUTION
# X_scaler = StandardScaler().fit(X_train)
# y_scaler = StandardScaler().fit(y_train)
# ### END SOLUTION

In [159]:
from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier

LinearRegression()

In [160]:
encoded_X = encoded_X.reshape(-1,1)
classifier.fit(encoded_X, y)

LinearRegression()

In [161]:
from sklearn.metrics import mean_squared_error, r2_score

# Use our model to predict a value
predicted = classifier.predict(encoded_X)

# Score the prediction with mse and r2
mse = mean_squared_error(y, predicted)
r2 = r2_score(y, predicted)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2 ): {r2}")

Mean Squared Error (MSE): 8218.742432633537
R-squared (R2 ): 0.0004382578052413155


In [162]:
predicted = classifier.predict(one_hot_X)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 1139)

In [163]:
print(predicted)

[30.6419335  30.66664494 30.66664494 ... 36.06609252 36.09698181
 36.12169324]


In [164]:
len(one_hot_X_feed1)

12

In [165]:
encoded_feed1 = encoded_feed1.reshape(-1,1)
classifier.predict(encoded_feed1)


array([35.00967886, 35.30621603, 33.76175162, 30.66664494, 30.9631821 ,
       32.61267009, 35.97342465, 32.05048505, 36.30085111, 35.50390747,
       34.7563867 , 35.95489108])

In [96]:
print(one_hot_X[1:2])
print(one_hot_X_feed1[1:2])


[[0. 0. 0. ... 0. 0. 0.]]
[[0.]]


In [20]:
len(df['description'].unique())

962

In [ ]:
# Step 0: Reformat data
data = df.values
# this is j in excel
X = data[:, 9]
# this is e in excel
y = data[:, 4]
print(y)

In [ ]:
# # Step 2: One-hot encoding
# one_hot_y = to_categorical(encoded_y)
# one_hot_y.shape